DefaultScene=HitmanBloodMoney.gms
ReadMainIni 0

# Audio pref
Audio_Volume_Sfx 100.000000
Audio_Volume_Dialog 100.000000
Audio_Volume_Music 100.000000
Audio_Volume_Ambience 100.000000
Audio_Volume_Movie 100.000000
UseEAX 0

# Controllers
//ConfigFile=Hitman_gamepad.cfg
//Gamepadmode
VibrationMode 0

# Colors
ColorDepth 32
GammaValue 1.000000

# Display
StartUpperPos 0,0
Window 0

# Textures
Anisotropy 16
DisableEMBM 0
DisableTrilinearFiltering 1
TextureResolution 0

# Other graphics options
Antialias 8
BlurShadows 1
DisableDropShadowBlur 0
DisableShaderCache
DisplayLights
DrawDistance 1.200000
GfxPostFilter 0
GfxPostFilterDepthBlur 0
LevelOfDetail 2
PostFilterLOD 2
RenderUsePartialPrecisionShader 0
SelfShadows 1
ShaderQuality VeryHigh
ShadowDetail 2
ShadowResolution 4096

# Misc
EnableConsole 1
WantBlood 1
Subtitles 1

#
