DefaultScene=AllLevels\Logos.gms
SoundDll SoundEngine.dll
ScriptDll sdl_engine.dll
scriptifdll scriptinterfaces.dll
DrawDll RenderD3D.dll
SoundRender Direct Sound (SW)

# Audio pref
MusicVolume 90
NumSoundBuffers 64
SoundEffectsVolume 90
SpeechVolume 90
UseEAX 0

# Controllers
//ConfigFile=HMCGPAD1.cfg
InvertMouse 0
//UseDirectInputMouse 1
//UseGameController
VibrationMode 0

# Colors
ColorDepth 32
GammaValue 1.000000

# Display
StartUpperPos 0,0
//Window 1

# Textures
Anisotropy 1
DisableBump 0
DisableDXT 1
DisableTrilinearFiltering 1
TextureResolution 0

# Other graphics options
Antialias 0
DisablePolyLimit
DrawDistance 1.000000
LevelOfDetail 2
PostFilterLOD 2
ShadowDetail 2
WeatherEffects 1
WeatherMultiplier 1.000000

# Misc
AutoDumpName dump0000.jpg
EnableConsole 1
Subtitles 1

#
