DefaultScene=AllLevels/Logos.gms
SoundDll SoundEngine.dll
ScriptDll SDL_Engine.dll
ScriptIfDll ScriptInterfaces.dll
DrawDll RenderD3D.dll
LocaleFile=Locale\English.xml

# Audio pref
MusicVolume 88
NumSoundBuffers 16
SoundEffectsVolume 100
SpeechVolume 100
UseEax 0

# Controllers
ConfigFile=Keyboard.cfg
EnableP5 0
MouseSpeed 0.8
//UseGameController
UseDirectInputMouse
UseDirectInputKeyboard

# Colors
ColorDepth 32
GammaValue 1.000000

# Display
Resolution 800x600
StartUpperPos 0,0
Window 0

# Textures
Anisotropy 1
DisableDXT
DisableTrilinearFiltering 1
TextureResolution 0

# Other graphics options
AntiAlias 0
DisableHWTnL 0
DisablePolyLimit
DrawDistance 1.200000
LevelOfDetail 2
ShadowDetail 2
WeatherEffects 1

# Misc
AutoDumpName ScreenDump0000.jpg
ErrorLog error.log
EnableConsole
HeroControlMode 1
Subtitles 1

#
