# bbport settings (in-game menu: Insert / L3+R3)
upscaler=fsr3
preset=0
sharpen=1
sharpness=0.50
object_motion=1
show_fps=0
output_res=1920x1080
model_lod=0
live_resolution=auto
effect_chromatic_aberration=0
effect_dof=1
effect_motion_blur=0
effect_ssao=1
effect_game_aa=0
effect_dynamic_shadows=1
effect_ssr=0
skip_intro=1
debug_camera=0
debug_menu=0
cheat_no_death=0
cheat_stealth=0
cheat_silent=0
cheat_rally_no_decay=0
cheat_enemy_control=0
tweak_no_rally=0
tweak_camera_distance=0
tweak_no_camera_rotation=0
tweak_easy_run=0
tweak_ragdoll=0
