Include Setup\Locale.zip
//DrawDll Render3DFX.dll
DrawDll renderd3d.dll
//DrawDll RenderOpenGL.dll
SoundDll Sound.dll
ScriptDll GSC.dll
LocaleDLL Locale.dll

# Colors
ColorDepth 32

# Display
Resolution 800x600
StartUpperPos 0,0
//Window

# Textures
Anisotropy 2
DisableDXT
TextureResolution 0

# Other graphics options
AntiAlias
ShadowDetail 2

# Misc
DisablePAL
enableconsole

#
